[package]
name = "discord_event_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
lambda_runtime = "0.14.4"
reqwest = { version = "0.12.24", features = ["blocking"] }
serde = "1.0.228"
serde_json = "1.0.145"
tokio = "1.48.0"
